# Generated by Django 5.2.16 on 2026-07-15 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeGmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rfc_message_id", models.CharField(max_length=255, unique=True)),
                ("gmail_message_id", models.CharField(max_length=255, unique=True)),
                ("gmail_thread_id", models.CharField(max_length=255)),
                ("recipient", models.CharField(max_length=320)),
                ("raw_message", models.BinaryField()),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="GmailConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=320)),
                ("scopes", models.JSONField(default=list)),
                ("refresh_token_encrypted", models.TextField(blank=True)),
                ("history_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Conectada"),
                            ("ERROR", "Con error"),
                            ("DISCONNECTED", "Desconectada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("token_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gmail_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
