# Generated by Django 5.2.16 on 2026-07-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("mailbox", "0002_fakegmailmessage_body_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundmessage",
            name="campaign_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_messages",
                to="contacts.campaignenrollment",
            ),
        ),
        migrations.AddField(
            model_name="inboundmessage",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_messages",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="inboundmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_messages",
                to="contacts.conversation",
            ),
        ),
        migrations.AddField(
            model_name="inboundmessage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_messages",
                to="contacts.organization",
            ),
        ),
    ]
