# Generated by Django 5.2.16 on 2026-07-16 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_outboundmessage_in_reply_to"),
        ("mailbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakegmailmessage",
            name="body_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="body_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="direction",
            field=models.CharField(
                choices=[("OUTBOUND", "Saliente"), ("INBOUND", "Entrante")],
                default="OUTBOUND",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="history_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="sender",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="fakegmailmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="fakegmailmessage",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="fakegmailmessage",
            name="raw_message",
            field=models.BinaryField(default=bytes),
        ),
        migrations.AlterField(
            model_name="fakegmailmessage",
            name="recipient",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gmail_message_id", models.CharField(max_length=255, unique=True)),
                ("gmail_thread_id", models.CharField(max_length=255)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("in_reply_to", models.CharField(blank=True, max_length=255)),
                ("references", models.JSONField(blank=True, default=list)),
                ("sender", models.CharField(max_length=320)),
                ("recipients", models.JSONField(default=list)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("external_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("body_text", models.TextField()),
                ("body_html_sanitized", models.TextField(blank=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("INTERESTED", "Interesado"),
                            ("NOT_INTERESTED", "No interesado"),
                            ("UNSUBSCRIBE", "Baja"),
                            ("AUTO_REPLY", "Respuesta automática"),
                            ("BOUNCE", "Rebote"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "classification_confidence",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("is_human", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                ("classification_error", models.TextField(blank=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_messages",
                        to="mailbox.gmailconnection",
                    ),
                ),
                (
                    "related_outbound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_messages",
                        to="campaigns.outboundmessage",
                    ),
                ),
            ],
            options={
                "ordering": ("-external_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["gmail_thread_id", "external_at"],
                        name="mailbox_inb_gmail_t_e37f42_idx",
                    ),
                    models.Index(
                        fields=["classification", "-external_at"],
                        name="mailbox_inb_classif_f4ff28_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("message_id", ""), _negated=True),
                        fields=("message_id",),
                        name="inbound_rfc_message_id_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("classification_confidence__gte", 0),
                            ("classification_confidence__lte", 1),
                        ),
                        name="inbound_classification_confidence_0_1",
                    ),
                ],
            },
        ),
    ]
