# Generated by Codex on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0017_outboundmessage_ineligible_state"),
        ("mailbox", "0004_gmail_connection_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundmessage",
            name="related_outbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_messages",
                to="campaigns.outboundmessage",
            ),
        ),
    ]
