# Generated by Django 5.2.16 on 2026-07-26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_workspace_memberships(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Workspace = apps.get_model("accounts", "Workspace")
    Membership = apps.get_model("accounts", "Membership")

    workspace, _ = Workspace.objects.get_or_create(singleton_key=1, defaults={"name": "Mi empresa"})
    users = list(User.objects.order_by("-is_active", "date_joined", "pk"))
    first_admin_id = users[0].pk if users else None
    Membership.objects.bulk_create(
        [
            Membership(
                workspace=workspace,
                user=user,
                role="ADMIN" if user.pk == first_admin_id else "VENDEDOR",
            )
            for user in users
        ],
        ignore_conflicts=True,
    )


def reverse_membership_backfill(apps, schema_editor):
    del apps, schema_editor
    # Existing users and history are intentionally preserved on rollback.


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("PAIR", "Usuario y dirección"), ("IP", "Dirección")],
                        max_length=10,
                    ),
                ),
                ("key_hash", models.CharField(max_length=64)),
                ("username_hash", models.CharField(blank=True, max_length=64)),
                ("ip_hash", models.CharField(max_length=64)),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "username_hash"], name="accounts_lo_scope_12a3cb_idx"
                    ),
                    models.Index(fields=["scope", "ip_hash"], name="accounts_lo_scope_50be67_idx"),
                    models.Index(fields=["locked_until"], name="accounts_lo_locked__87543f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_hash"), name="login_throttle_scope_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("failure_count__gte", 0)),
                        name="login_throttle_failure_count_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
                ),
                ("name", models.CharField(default="Mi empresa", max_length=160)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton_key", 1)), name="workspace_is_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Administrador"), ("VENDEDOR", "Vendedor")],
                        max_length=20,
                    ),
                ),
                ("session_version", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={"ordering": ("user__username",)},
        ),
        migrations.RunPython(backfill_workspace_memberships, reverse_membership_backfill),
        migrations.CreateModel(
            name="ActivationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ACTIVATE", "Activación"), ("RESET", "Cambio de contraseña")],
                        default="ACTIVATE",
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_activation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["token_hash", "expires_at"], name="accounts_ac_token_h_46777f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(max_length=255)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["membership", "used_at"], name="accounts_re_members_9e9f1d_idx"
                    )
                ],
            },
        ),
    ]
