# Generated by Django 5.2.16 on 2026-07-15 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0002_aianalysis_websitesnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysis",
            name="generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="regeneration_nonce",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="aianalysis",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_ai_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="analysis_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospect",
            name="pipeline_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="pipeline_reservation_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="prospect",
            name="pipeline_reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aianalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("VALID", "Válido"),
                    ("RETRY_WAIT", "Esperando reintento"),
                    ("ERROR", "Error"),
                ],
                max_length=20,
            ),
        ),
    ]
