# Generated by Django 5.2.16 on 2026-07-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("prospects", "0004_website_email_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="campaign_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_prospects",
                to="contacts.campaignenrollment",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_prospects",
                to="contacts.organization",
            ),
        ),
    ]
