# Generated by Django 5.2.17 on 2026-10-06 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0005_prospect_campaign_enrollment_prospect_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="relevance_override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="relevance_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restored_prospects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="pipeline_state",
            field=models.CharField(
                choices=[
                    ("DISCOVERED", "Descubierto"),
                    ("EMAIL_FOUND", "Email encontrado"),
                    ("ENRICHED", "Enriquecido"),
                    ("ANALYZED", "Analizado"),
                    ("SKIPPED_NO_EMAIL", "Sin email"),
                    ("SKIPPED_DUPLICATE", "Duplicado"),
                    ("SKIPPED_IRRELEVANT", "Descartado por el filtro"),
                    ("QUEUED", "En cola"),
                    ("ERROR", "Error"),
                ],
                default="DISCOVERED",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProspectRelevanceVerdict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_hash", models.CharField(max_length=64)),
                ("criteria_digest", models.CharField(max_length=64)),
                ("snapshot_content_hash", models.CharField(blank=True, max_length=64)),
                ("mode", models.CharField(max_length=20)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[("FIT", "Encaja"), ("UNCLEAR", "Dudoso"), ("UNFIT", "No encaja")],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("vetoed", models.BooleanField(default=False)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=120)),
                ("schema_version", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("VALID", "Válido"), ("ERROR", "Error"), ("SKIPPED", "Omitido")],
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("evaluated_at", models.DateTimeField()),
                ("input_characters", models.PositiveIntegerField(default=0)),
                ("request_manifest", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relevance_verdicts",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ("-evaluated_at",),
                "indexes": [
                    models.Index(
                        fields=["prospect", "-evaluated_at"], name="prospects_p_prospec_026434_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prospect", "input_hash", "provider", "model"),
                        name="prospect_relevance_cache_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "VALID"), _negated=True),
                            ("verdict__in", ("FIT", "UNCLEAR", "UNFIT")),
                            _connector="OR",
                        ),
                        name="prospect_relevance_valid_has_verdict",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("vetoed", False),
                            ("verdict__in", ("UNFIT", "UNCLEAR")),
                            _connector="OR",
                        ),
                        name="prospect_relevance_veto_requires_negative_verdict",
                    ),
                ],
            },
        ),
    ]
