# Generated by Django 5.2.16 on 2026-07-26 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("automation", "0001_initial"),
        ("contacts", "0002_backfill_contact_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomaticActionReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reserved_at", models.DateTimeField()),
                ("local_date", models.DateField()),
                ("slots", models.PositiveSmallIntegerField(default=1)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automatic_action_reservations",
                        to="contacts.conversation",
                    ),
                ),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automatic_action_reservation",
                        to="automation.replydecision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automatic_action_reservations",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["conversation", "reserved_at"],
                        name="automation__convers_0e5d6c_idx",
                    ),
                    models.Index(
                        fields=["workspace", "local_date"], name="automation__workspa_d98910_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slots__gte", 1), ("slots__lte", 2)),
                        name="automatic_action_reservation_slots_1_2",
                    )
                ],
            },
        ),
    ]
