# Generated by Django 5.2.16 on 2026-07-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_automatic_action_reservations"),
        ("contacts", "0002_backfill_contact_foundation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticactionreservation",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="automatic_action_reservations",
                to="contacts.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="automaticactionreservation",
            name="decision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="automatic_action_reservation",
                to="automation.replydecision",
            ),
        ),
        migrations.AlterField(
            model_name="humantask",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="human_tasks",
                to="contacts.conversation",
            ),
        ),
        migrations.AddField(
            model_name="scheduledcontactattempt",
            name="context_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="scheduledcontactattempt",
            name="context_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scheduledcontactattempt",
            name="fact_revision_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="scheduledcontactattempt",
            name="model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scheduledcontactattempt",
            name="provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="automaticactionreservation",
            name="scheduled_attempt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="automatic_action_reservation",
                to="automation.scheduledcontactattempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="automaticactionreservation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        decision__isnull=False,
                        conversation__isnull=False,
                        scheduled_attempt__isnull=True,
                    )
                    | models.Q(decision__isnull=True, scheduled_attempt__isnull=False)
                ),
                name="automatic_action_reservation_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="humantask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status="OPEN",
                    inbound__isnull=True,
                    conversation__isnull=True,
                ),
                fields=("contact", "kind", "reason"),
                name="open_contact_task_kind_reason_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="humantask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status="OPEN",
                    inbound__isnull=True,
                    conversation__isnull=False,
                ),
                fields=("conversation", "kind", "reason"),
                name="open_conversation_task_kind_reason_unique",
            ),
        ),
    ]
