# Generated by Django 5.2.16 on 2026-07-28 02:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("automation", "0003_scheduled_contact_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeFactEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=120)),
                (
                    "dimensions",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(64),
                            django.core.validators.MaxValueValidator(3072),
                        ]
                    ),
                ),
                ("input_hash", models.CharField(max_length=64)),
                ("vector", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[("READY", "Lista"), ("FAILED", "No se pudo generar")],
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("embedded_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="automation.knowledgefactrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("revision", "provider", "model", "dimensions"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("revision", "provider", "model", "dimensions"),
                        name="knowledge_embedding_revision_provider_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("dimensions__gte", 64), ("dimensions__lte", 3072)),
                        name="knowledge_embedding_dimensions_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceKnowledgeContextRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("context_text", models.TextField(max_length=4000)),
                ("source_notes", models.TextField(blank=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_workspace_knowledge_context_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_context_revisions",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("workspace", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "version"),
                        name="workspace_knowledge_context_revision_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("approved_at__isnull", True), ("approved_by__isnull", True)),
                            models.Q(
                                ("approved_at__isnull", False), ("approved_by__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="workspace_knowledge_context_approval_consistent",
                    ),
                ],
            },
        ),
    ]
