# Generated by Codex on 2026-07-31

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PURPOSE_LABELS = {
    "CHECK_IN": "Preguntar cómo está",
    "PRODUCT_FEEDBACK": "Pedir opinión sobre el producto",
    "ADMIN_GOAL": "Objetivo personalizado",
}
PURPOSE_OBJECTIVES = {
    "CHECK_IN": "Preguntar de manera cordial cómo están y si hay algo en lo que podamos ayudar.",
    "PRODUCT_FEEDBACK": (
        "Pedir una opinión general sobre el producto o la atención, sin asumir detalles."
    ),
}


def forwards(apps, schema_editor):
    FollowUpTopic = apps.get_model("automation", "FollowUpTopic")
    ContactCommunicationPlan = apps.get_model("automation", "ContactCommunicationPlan")
    for plan in ContactCommunicationPlan.objects.select_related("contact").order_by("created_at"):
        base_name = PURPOSE_LABELS.get(plan.purpose, "Seguimiento")
        if plan.purpose == "ADMIN_GOAL" and plan.goal_text.strip():
            base_name = f"Objetivo: {plan.goal_text.strip()[:80]}"
        name = f"{base_name} ({str(plan.pk)[:8]})"[:160]
        objective = (plan.goal_text.strip() or PURPOSE_OBJECTIVES.get(plan.purpose, base_name))[
            :1000
        ]
        topic = FollowUpTopic.objects.create(
            workspace_id=plan.contact.workspace_id,
            name=name,
            objective=objective,
            instructions="",
            cadence_days=max(int(plan.cadence_days or 30), 7),
            mode=plan.mode or "REVIEW_BEFORE_SEND",
            next_due_at=plan.next_due_at,
            active=plan.state != "DISABLED",
            created_by_id=plan.created_by_id,
            updated_by_id=plan.updated_by_id,
        )
        plan.topic_id = topic.pk
        plan.save(update_fields=("topic",))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("automation", "0004_knowledgefactembedding_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("objective", models.TextField(max_length=1000)),
                ("instructions", models.TextField(blank=True, max_length=2000)),
                (
                    "cadence_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(7)],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("REVIEW_BEFORE_SEND", "Revisar antes de enviar"),
                            ("AUTOMATIC", "Enviar automáticamente"),
                        ],
                        default="REVIEW_BEFORE_SEND",
                        max_length=30,
                    ),
                ),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_follow_up_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_follow_up_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_up_topics",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "name"),
                        name="follow_up_topic_workspace_name_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cadence_days__gte", 7)),
                        name="follow_up_topic_cadence_minimum",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["workspace", "active", "next_due_at"],
                        name="auto_topic_due_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="contactcommunicationplan",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_approvals",
                to="automation.followuptopic",
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="contactcommunicationplan",
            name="contact_plan_cadence_minimum",
        ),
        migrations.RemoveField(
            model_name="contactcommunicationplan",
            name="cadence_days",
        ),
        migrations.RemoveField(
            model_name="contactcommunicationplan",
            name="goal_text",
        ),
        migrations.RemoveField(
            model_name="contactcommunicationplan",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="contactcommunicationplan",
            name="purpose",
        ),
        migrations.AlterField(
            model_name="contactcommunicationplan",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="communication_plans",
                to="contacts.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contactcommunicationplan",
            name="preferred_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="follow_up_topic_approvals",
                to="contacts.emailaddress",
            ),
        ),
        migrations.AlterField(
            model_name="contactcommunicationplan",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact_approvals",
                to="automation.followuptopic",
            ),
        ),
        migrations.AddIndex(
            model_name="contactcommunicationplan",
            index=models.Index(
                fields=["contact", "state", "next_due_at"],
                name="auto_plan_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactcommunicationplan",
            constraint=models.UniqueConstraint(
                fields=("contact", "topic"),
                name="contact_follow_up_topic_unique",
            ),
        ),
    ]
