# Generated by Django 5.2.16 on 2026-07-15 14:05

import apps.campaigns.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        ("configuration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("RUNNING", "En curso"),
                            ("PAUSED", "Pausada"),
                            ("CANCELLED", "Cancelada"),
                            ("COMPLETED", "Completada"),
                            ("STOPPED_ERROR", "Detenida por error"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "discovery_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En curso"),
                            ("TARGET_REACHED", "Objetivo alcanzado"),
                            ("EXHAUSTED_QUERIES", "Consultas agotadas"),
                            ("EXHAUSTED_RAW_LIMIT", "Límite crudo agotado"),
                            ("EXHAUSTED_COST", "Costo agotado"),
                            ("FAILED_PROVIDER", "Proveedor falló"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("discovery_stop_reason", models.CharField(blank=True, max_length=200)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[("DRY_RUN", "Simulación"), ("LIVE", "En vivo")],
                        default="DRY_RUN",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.TextField(blank=True)),
                (
                    "location_text",
                    models.CharField(
                        default="Ciudad Autónoma de Buenos Aires, Argentina", max_length=300
                    ),
                ),
                ("objective", models.PositiveIntegerField(default=300)),
                ("max_raw_records", models.PositiveIntegerField(default=3000)),
                (
                    "cost_limit",
                    models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=12),
                ),
                ("cost_currency", models.CharField(default="USD", max_length=3)),
                ("daily_limit", models.PositiveIntegerField(default=30)),
                ("message_interval_minutes", models.PositiveIntegerField(default=5)),
                ("weekdays", models.JSONField(default=apps.campaigns.models.default_weekdays)),
                ("window_start", models.TimeField(default="09:00")),
                ("window_end", models.TimeField(default="17:00")),
                (
                    "timezone_name",
                    models.CharField(default="America/Argentina/Buenos_Aires", max_length=64),
                ),
                ("relevance_threshold", models.PositiveSmallIntegerField(default=70)),
                ("extractor_provider", models.CharField(default="fake", max_length=50)),
                ("llm_provider", models.CharField(default="fake", max_length=50)),
                ("llm_base_url", models.URLField(blank=True)),
                ("llm_model", models.CharField(default="fake-deterministic", max_length=120)),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
                ("profile_snapshot", models.JSONField(blank=True, default=dict)),
                ("prompt_snapshot", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="catalogs.catalog",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CampaignCategorySelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_snapshot", models.CharField(max_length=160)),
                ("normalized_name_snapshot", models.CharField(max_length=160)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_selections",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_selections",
                        to="configuration.searchcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name_snapshot"),
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="categories",
            field=models.ManyToManyField(
                through="campaigns.CampaignCategorySelection", to="configuration.searchcategory"
            ),
        ),
        migrations.CreateModel(
            name="CampaignZoneSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_snapshot", models.CharField(max_length=160)),
                ("location_snapshot", models.CharField(max_length=300)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_selections",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_selections",
                        to="configuration.searchzone",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name_snapshot"),
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="zones",
            field=models.ManyToManyField(
                through="campaigns.CampaignZoneSelection", to="configuration.searchzone"
            ),
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_snapshot", models.CharField(max_length=160)),
                ("zone_snapshot", models.CharField(max_length=160)),
                ("location_snapshot", models.CharField(max_length=300)),
                ("query_text", models.CharField(max_length=700)),
                ("normalized_query", models.CharField(max_length=700)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En curso"),
                            ("SUCCEEDED", "Completada"),
                            ("RETRY_WAIT", "Esperando reintento"),
                            ("FAILED_PERMANENT", "Falló"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.AddConstraint(
            model_name="campaigncategoryselection",
            constraint=models.UniqueConstraint(
                fields=("campaign", "category"), name="campaign_category_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignzoneselection",
            constraint=models.UniqueConstraint(
                fields=("campaign", "zone"), name="campaign_zone_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["state", "-created_at"], name="campaigns_c_state_9c43ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("objective__gt", 0)), name="campaign_objective_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_raw_records__gt", 0)), name="campaign_raw_limit_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_limit__gte", 0)), name="campaign_cost_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_limit__gt", 0)), name="campaign_daily_limit_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("message_interval_minutes__gt", 0)),
                name="campaign_interval_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("relevance_threshold__gte", 0), ("relevance_threshold__lte", 100)
                ),
                name="campaign_relevance_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchquery",
            constraint=models.UniqueConstraint(
                fields=("campaign", "normalized_query"), name="campaign_query_unique"
            ),
        ),
    ]
