# Generated by Django 5.2.16 on 2026-07-15 15:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("request_json", models.JSONField(default=dict)),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("response_hash", models.CharField(blank=True, max_length=64)),
                ("provider_request_id", models.CharField(blank=True, max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En curso"),
                            ("SUCCEEDED", "Completada"),
                            ("RETRY_WAIT", "Esperando reintento"),
                            ("FAILED_PERMANENT", "Falló permanentemente"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("cursor", models.CharField(blank=True, max_length=500)),
                ("requested_limit", models.PositiveIntegerField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("raw_count", models.PositiveIntegerField(default=0)),
                ("email_count", models.PositiveIntegerField(default=0)),
                ("no_email_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "cost_reserved",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=14),
                ),
                (
                    "cost_estimated",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                (
                    "cost_actual",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("raw_persisted_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("next_poll_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_runs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="campaigns.searchquery",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProviderUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=100)),
                (
                    "units",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                (
                    "actual_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                ("currency", models.CharField(max_length=3)),
                ("request_id", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_usage",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage",
                        to="campaigns.searchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="searchrun",
            index=models.Index(
                fields=["state", "next_poll_at"], name="campaigns_s_state_aa408f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchrun",
            index=models.Index(fields=["campaign", "state"], name="campaigns_s_campaig_2bbce1_idx"),
        ),
        migrations.AddConstraint(
            model_name="searchrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_request_id", ""), _negated=True),
                fields=("provider", "provider_request_id"),
                name="provider_request_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_reserved__gte", 0)),
                name="search_run_reserved_cost_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="providerusage",
            index=models.Index(
                fields=["provider", "campaign", "created_at"], name="campaigns_p_provide_cbac5c_idx"
            ),
        ),
    ]
