# Generated by Django 5.2.16 on 2026-07-15 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_campaign_outscraper_cost_usd"),
        ("catalogs", "0001_initial"),
        ("prospects", "0002_aianalysis_websitesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FIRST_CONTACT", "Primer contacto"),
                            ("MANUAL_REPLY", "Respuesta manual"),
                        ],
                        default="FIRST_CONTACT",
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(max_length=320)),
                ("recipient_normalized", models.CharField(max_length=320)),
                ("subject", models.CharField(max_length=255)),
                ("body_text", models.TextField()),
                ("catalog_version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PREPARED", "Preparado"),
                            ("QUEUED", "En cola"),
                            ("SENDING", "Enviando"),
                            ("RECONCILING", "Reconciliando"),
                            ("SENT", "Enviado"),
                            ("DRY_RUN_COMPLETED", "Simulado"),
                            ("SEND_FAILED", "Falló"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PREPARED",
                        max_length=30,
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[("DRY_RUN", "Simulación"), ("LIVE", "En vivo")], max_length=20
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("contact_sequence", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_message",
                        to="prospects.aianalysis",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="catalogs.catalog",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_messages",
                        to="prospects.prospect",
                    ),
                ),
                (
                    "prospect_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_messages",
                        to="prospects.prospectemail",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["campaign", "state"], name="campaigns_o_campaig_f9135f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("contact_sequence__isnull", False), ("kind", "FIRST_CONTACT")
                        ),
                        fields=("recipient_normalized", "contact_sequence"),
                        name="first_contact_email_sequence_unique",
                    )
                ],
            },
        ),
    ]
