# Generated by Django 5.2.16 on 2026-07-16 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_outboundmessage_in_reply_to"),
        ("mailbox", "0002_fakegmailmessage_body_html_and_more"),
        ("prospects", "0003_aianalysis_generation_aianalysis_next_retry_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="parent_inbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manual_replies",
                to="mailbox.inboundmessage",
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="references",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manual_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="analysis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_message",
                to="prospects.aianalysis",
            ),
        ),
    ]
