# Generated by Django 5.2.16 on 2026-07-16 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_outboundmessage_parent_inbound_and_more"),
        ("catalogs", "0001_initial"),
        ("mailbox", "0002_fakegmailmessage_body_html_and_more"),
        ("prospects", "0003_aianalysis_generation_aianalysis_next_retry_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="outboundmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "MANUAL_REPLY"), ("parent_inbound__isnull", False)),
                fields=("parent_inbound",),
                name="manual_reply_parent_inbound_unique",
            ),
        ),
    ]
