# Generated by Django 5.2.16 on 2026-07-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0011_outbound_manual_approval"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="campaign_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_messages",
                to="contacts.campaignenrollment",
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_messages",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_messages",
                to="contacts.conversation",
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_messages",
                to="contacts.organization",
            ),
        ),
    ]
