# Generated by Django 5.2.17 on 2026-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0017_outboundmessage_ineligible_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="initial_body_snapshot",
            field=models.TextField(
                default="Buen día:\n\nNos ponemos en contacto para acercarle nuestra propuesta de componentes industriales y compartir nuestros catálogos. Trabajamos con distintas medidas y aplicaciones para equipos y herramientas eléctricas. Si le resulta de interés, puede responder este correo y con gusto ampliaremos la información.\n\nSaludos."
            ),
        ),
    ]
