# Generated by Django 5.2.16 on 2026-07-15 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0002_searchrun_providerusage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("normalized_name", models.CharField(max_length=300)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("normalized_address", models.CharField(blank=True, max_length=500)),
                ("neighborhood", models.CharField(blank=True, max_length=160)),
                ("category", models.CharField(blank=True, max_length=160)),
                ("website", models.URLField(blank=True, max_length=1000)),
                ("business_domain", models.CharField(blank=True, max_length=253)),
                ("phone", models.CharField(blank=True, max_length=80)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("provider_data", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline_state",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "Descubierto"),
                            ("EMAIL_FOUND", "Email encontrado"),
                            ("ENRICHED", "Enriquecido"),
                            ("ANALYZED", "Analizado"),
                            ("SKIPPED_NO_EMAIL", "Sin email"),
                            ("SKIPPED_DUPLICATE", "Duplicado"),
                            ("SKIPPED_IRRELEVANT", "Irrelevante"),
                            ("QUEUED", "En cola"),
                            ("ERROR", "Error"),
                        ],
                        default="DISCOVERED",
                        max_length=30,
                    ),
                ),
                ("error_stage", models.CharField(blank=True, max_length=50)),
                ("last_error", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prospects",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prospects",
                        to="campaigns.searchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProspectEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_email", models.CharField(max_length=320)),
                ("normalized_email", models.CharField(max_length=320, unique=True)),
                ("domain", models.CharField(max_length=253)),
                ("local_part", models.CharField(max_length=64)),
                ("source", models.CharField(max_length=120)),
                ("provider_order", models.PositiveIntegerField(default=0)),
                ("syntax_valid", models.BooleanField(default=True)),
                (
                    "mx_status",
                    models.CharField(
                        choices=[
                            ("VALID", "Válido"),
                            ("INVALID", "Inválido"),
                            ("TRANSIENT", "Error temporal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mx_checked_at", models.DateTimeField()),
                ("exclusion_reason", models.CharField(blank=True, max_length=120)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_invalid", models.BooleanField(default=False)),
                ("invalid_reason", models.CharField(blank=True, max_length=200)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ("provider_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ProspectIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("BUSINESS_DOMAIN", "Dominio empresarial"),
                            ("PROVIDER_ID", "Identificador del proveedor"),
                            ("NAME_ADDRESS", "Nombre y dirección"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value_hash", models.CharField(max_length=64)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="prospects.prospect",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["campaign", "pipeline_state"], name="prospects_p_campaig_fdf323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(fields=["business_domain"], name="prospects_p_busines_7c7c20_idx"),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(fields=["normalized_name"], name="prospects_p_normali_042138_idx"),
        ),
        migrations.AddConstraint(
            model_name="prospectemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("prospect",),
                name="prospect_one_primary_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="prospectidentity",
            constraint=models.UniqueConstraint(
                fields=("kind", "value_hash"), name="prospect_identity_global_unique"
            ),
        ),
    ]
