# Generated by Django 5.2.16 on 2026-07-15 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_hash", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=40)),
                ("schema_version", models.CharField(max_length=40)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=120)),
                ("analyzed_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("VALID", "Válido"), ("ERROR", "Error")], max_length=20
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("relevance_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
                ),
                ("relevance_reason", models.TextField(blank=True)),
                ("evidence", models.JSONField(default=list)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body_text", models.TextField(blank=True)),
                ("prompt_text", models.TextField()),
                ("output_json", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ("-analyzed_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "input_hash",
                            "prompt_version",
                            "schema_version",
                            "provider",
                            "model",
                        ),
                        name="ai_analysis_cache_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("relevance_score__isnull", True),
                            models.Q(("relevance_score__gte", 0), ("relevance_score__lte", 100)),
                            _connector="OR",
                        ),
                        name="ai_analysis_relevance_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__isnull", True),
                            models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                            _connector="OR",
                        ),
                        name="ai_analysis_confidence_0_1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_url", models.URLField(blank=True, max_length=1000)),
                ("final_url", models.URLField(blank=True, max_length=1000)),
                ("fetched_at", models.DateTimeField()),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("content_hash", models.CharField(max_length=64)),
                ("excerpt", models.TextField(blank=True)),
                ("pages", models.JSONField(default=list)),
                ("byte_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Exitoso"),
                            ("PARTIAL", "Parcial"),
                            ("FALLBACK", "Sin contexto web"),
                            ("REJECTED", "URL rechazada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="web_snapshots",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "ordering": ("-fetched_at",),
                "indexes": [
                    models.Index(
                        fields=["prospect", "-fetched_at"], name="prospects_w_prospec_253685_idx"
                    ),
                    models.Index(fields=["content_hash"], name="prospects_w_content_a82773_idx"),
                ],
            },
        ),
    ]
