# Generated by Django 5.2.16 on 2026-07-15 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_email", models.EmailField(max_length=320)),
                ("normalized_email", models.CharField(editable=False, max_length=320, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNSUBSCRIBE", "Baja"),
                            ("BOUNCE", "Rebote"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="dashboard", max_length=100)),
                ("evidence", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppression_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
