# Generated by Django 5.2.16 on 2026-07-15 14:05

import apps.catalogs.models
import apps.catalogs.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=apps.catalogs.storage.PrivateCatalogStorage(),
                        upload_to=apps.catalogs.models.catalog_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("detected_mime", models.CharField(max_length=100)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("missing", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="catalog_name_version_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("byte_size__gt", 0)), name="catalog_size_positive"
                    ),
                ],
            },
        ),
    ]
