# Generated by Django 5.2.16 on 2026-07-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0003_integrationconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_query_template",
                    models.TextField(default="{category} en {zone}, {location}"),
                ),
                (
                    "email_drafting_prompt",
                    models.TextField(
                        default=(
                            "Priorizá un tono profesional, directo y prudente. Explicá una "
                            "relación posible con los productos del perfil sin asumir que el "
                            "negocio ya los compra o necesita."
                        )
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompt_configuration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
