# Generated by Django 5.2.16 on 2026-07-26 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("campaigns", "0011_outbound_manual_approval"),
        ("mailbox", "0002_fakegmailmessage_body_html_and_more"),
        ("prospects", "0004_website_email_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("normalized_name", models.CharField(blank=True, max_length=300)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("normalized_address", models.CharField(blank=True, max_length=500)),
                ("website", models.URLField(blank=True, max_length=1000)),
                ("business_domain", models.CharField(blank=True, max_length=253)),
                ("phone", models.CharField(blank=True, max_length=80)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DISCOVERY", "Descubrimiento"),
                            ("INBOUND", "Respuesta recibida"),
                            ("MANUAL", "Carga manual"),
                            ("SUPPRESSION", "Restricción anterior"),
                            ("MIGRATION", "Datos existentes"),
                        ],
                        default="DISCOVERY",
                        max_length=20,
                    ),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("normalized_name", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_email", models.CharField(max_length=320)),
                ("normalized_email", models.CharField(max_length=320)),
                ("domain", models.CharField(blank=True, max_length=253)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("is_preferred", models.BooleanField(default=False)),
                ("provenance", models.CharField(blank=True, max_length=120)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("source_content_hash", models.CharField(blank=True, max_length=64)),
                ("provider_order", models.PositiveIntegerField(default=0)),
                (
                    "validity",
                    models.CharField(
                        choices=[
                            ("VALID", "Válido"),
                            ("INVALID", "Inválido"),
                            ("TRANSIENT", "Validación pendiente"),
                            ("UNKNOWN", "Sin validar"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("invalid_reason", models.CharField(blank=True, max_length=200)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legacy_prospect_email",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_email_address",
                        to="prospects.prospectemail",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_addresses",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_addresses",
                        to="contacts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("provider_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Contacto actual"),
                            ("DO_NOT_CONTACT", "No contactar"),
                            ("UNSUBSCRIBED", "Baja solicitada"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_reason",
                    models.CharField(
                        choices=[
                            ("HUMAN_REPLY", "Respondió una persona"),
                            ("MANUAL_ENTRY", "Carga manual"),
                            ("MANUAL_RESTRICTION", "Restricción manual"),
                            ("UNSUBSCRIBE", "Baja solicitada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_inbound_message_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("automation_suspended", models.BooleanField(default=False)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "preferred_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferred_for_contacts",
                        to="contacts.emailaddress",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact",
                        to="contacts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_interaction_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="CampaignEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "Descubierto"),
                            ("ELIGIBLE", "Puede recibir la propuesta"),
                            ("PREPARED", "Mensaje preparado"),
                            ("INITIAL_SENT", "Propuesta enviada"),
                            ("RESPONDED", "Respondió"),
                            ("REMINDER_DUE", "Recordatorio pendiente"),
                            ("REMINDER_SENT", "Recordatorio enviado"),
                            ("INELIGIBLE", "No se puede contactar"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DISCOVERED",
                        max_length=30,
                    ),
                ),
                ("source", models.CharField(default="LEGACY_PROSPECT", max_length=50)),
                ("exclusion_reason", models.CharField(blank=True, max_length=200)),
                ("initial_sent_at", models.DateTimeField(blank=True, null=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_enrollments",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "selected_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_enrollments",
                        to="contacts.emailaddress",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_enrollments",
                        to="contacts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("campaign", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="OrganizationIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GERS_ID", "GERS ID"),
                            ("PROVIDER_ID", "Identificador del proveedor"),
                            ("BUSINESS_DOMAIN", "Dominio empresarial"),
                            ("NAME_ADDRESS", "Nombre y dirección"),
                            ("EMAIL", "Email heredado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=1000)),
                ("value_hash", models.CharField(max_length=64)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="contacts.organization",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_identities",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("kind", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gmail_thread_id", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("automation_suspended", models.BooleanField(default=False)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="mailbox.gmailconnection",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="contacts.contact",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_message_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["contact", "-last_message_at"],
                        name="contacts_co_contact_d38a0c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "gmail_thread_id"),
                        name="gmail_connection_thread_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("CONTACT", "Todo el contacto"), ("EMAIL", "Sólo este email")],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("UNSUBSCRIBE", "Baja"),
                            ("BOUNCE", "Rebote"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("evidence", models.TextField(blank=True)),
                ("source_inbound_message_id", models.UUIDField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_communication_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_communication_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communication_restrictions",
                        to="accounts.workspace",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restrictions",
                        to="contacts.contact",
                    ),
                ),
                (
                    "email_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restrictions",
                        to="contacts.emailaddress",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["workspace", "kind", "revoked_at"],
                        name="contacts_co_workspa_924c47_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("contact__isnull", False),
                                ("email_address__isnull", True),
                                ("scope", "CONTACT"),
                            ),
                            models.Q(
                                ("contact__isnull", True),
                                ("email_address__isnull", False),
                                ("scope", "EMAIL"),
                            ),
                            _connector="OR",
                        ),
                        name="restriction_scope_target_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "BOUNCE"), _negated=True),
                            ("scope", "EMAIL"),
                            _connector="OR",
                        ),
                        name="bounce_restriction_email_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind", "UNSUBSCRIBE"), ("revoked_at__isnull", False), _negated=True
                        ),
                        name="unsubscribe_restriction_permanent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revocation_reason", ""),
                                ("revoked_at__isnull", True),
                                ("revoked_by__isnull", True),
                            ),
                            models.Q(
                                ("revoked_at__isnull", False),
                                ("revoked_by__isnull", False),
                                models.Q(("revocation_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="restriction_revocation_audited",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("contact__isnull", False), ("revoked_at__isnull", True)
                        ),
                        fields=("contact", "kind"),
                        name="active_contact_restriction_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("email_address__isnull", False), ("revoked_at__isnull", True)
                        ),
                        fields=("email_address", "kind"),
                        name="active_email_restriction_unique",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["workspace", "normalized_name"], name="contacts_or_workspa_ef99f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["workspace", "business_domain"], name="contacts_or_workspa_efa167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailaddress",
            index=models.Index(
                fields=["organization", "validity"], name="contacts_em_organiz_b17794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailaddress",
            index=models.Index(
                fields=["workspace", "normalized_email"], name="contacts_em_workspa_f83132_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailaddress",
            constraint=models.UniqueConstraint(
                fields=("workspace", "normalized_email"), name="email_address_workspace_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred", True)),
                fields=("organization",),
                name="organization_one_preferred_email",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["workspace", "status"], name="contacts_co_workspa_bd58fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignenrollment",
            index=models.Index(fields=["campaign", "state"], name="contacts_ca_campaig_614c42_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignenrollment",
            index=models.Index(
                fields=["organization", "-created_at"], name="contacts_ca_organiz_845e3a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignenrollment",
            constraint=models.UniqueConstraint(
                fields=("campaign", "organization"), name="campaign_organization_enrollment_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("selected_email__isnull", False)),
                fields=("campaign", "selected_email"),
                name="campaign_email_enrollment_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationidentity",
            index=models.Index(
                fields=["organization", "kind"], name="contacts_or_organiz_b3a896_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationidentity",
            constraint=models.UniqueConstraint(
                fields=("workspace", "kind", "value_hash"), name="org_identity_workspace_unique"
            ),
        ),
    ]
