# Generated by Django 5.2.16 on 2026-07-24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OvertureDatasetSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("release_id", models.CharField(db_index=True, max_length=40)),
                ("schema_version", models.CharField(max_length=80)),
                ("taxonomy_version", models.CharField(max_length=80)),
                ("importer_version", models.CharField(max_length=80)),
                ("mapping_version", models.CharField(max_length=80)),
                ("boundary_version", models.CharField(max_length=120)),
                ("boundary_manifest_sha256", models.CharField(max_length=64)),
                ("source_uri", models.CharField(max_length=500)),
                ("manifest_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IMPORTING", "Importando"),
                            ("READY", "Listo"),
                            ("SUPERSEDED", "Reemplazado"),
                            ("FAILED", "Falló"),
                        ],
                        default="IMPORTING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("streamed_count", models.PositiveIntegerField(default=0)),
                ("place_count", models.PositiveIntegerField(default=0)),
                ("zone_count", models.PositiveIntegerField(default=0)),
                ("taxonomy_code_count", models.PositiveIntegerField(default=0)),
                ("source_counts", models.JSONField(default=dict)),
                ("source_licenses", models.JSONField(default=list)),
                ("attribution", models.TextField(blank=True)),
                ("notices", models.JSONField(default=list)),
                ("validation_results", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="overture_snap_status_idx"),
                    models.Index(
                        fields=["release_id", "mapping_version", "boundary_version"],
                        name="overture_snap_versions_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="overture_one_active_snapshot",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_active", False), ("status", "READY"), _connector="OR"
                        ),
                        name="overture_active_is_ready",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "READY"), _negated=True),
                            ("is_active", True),
                            _connector="OR",
                        ),
                        name="overture_ready_is_active",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OverturePlace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("overture_id", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=300)),
                ("normalized_name", models.CharField(max_length=300)),
                ("name_search", models.CharField(max_length=320)),
                ("names", models.JSONField(default=dict)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("address_data", models.JSONField(default=dict)),
                ("websites", models.JSONField(default=list)),
                ("emails", models.JSONField(default=list)),
                ("phones", models.JSONField(default=list)),
                ("primary_category", models.CharField(blank=True, max_length=160)),
                ("basic_category", models.CharField(blank=True, max_length=160)),
                ("taxonomy", models.JSONField(default=dict)),
                ("taxonomy_codes", models.JSONField(default=list)),
                ("taxonomy_codes_search", models.TextField(blank=True)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("operating_status", models.CharField(blank=True, max_length=40)),
                ("sources", models.JSONField(default=list)),
                ("field_provenance", models.JSONField(default=dict)),
                ("source_licenses", models.JSONField(default=list)),
                ("license", models.CharField(blank=True, max_length=500)),
                ("source_payload_hash", models.CharField(max_length=64)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="overture.overturedatasetsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "overture_id"),
                "indexes": [
                    models.Index(
                        fields=["snapshot", "primary_category"], name="overture_place_category_idx"
                    ),
                    models.Index(
                        fields=["snapshot", "normalized_name"], name="overture_place_name_idx"
                    ),
                    models.Index(
                        fields=["snapshot", "latitude", "longitude"],
                        name="overture_place_coords_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "overture_id"), name="overture_place_snapshot_id_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                        name="overture_place_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                        name="overture_place_longitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__isnull", True),
                            models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                            _connector="OR",
                        ),
                        name="overture_place_confidence_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OvertureTaxonomyCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=160)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("parent_code", models.CharField(blank=True, max_length=160)),
                ("hierarchy", models.JSONField(default=list)),
                ("alternate_codes", models.JSONField(default=list)),
                ("is_basic_category", models.BooleanField(default=False)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomy_codes",
                        to="overture.overturedatasetsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "code"),
                        name="overture_taxonomy_snapshot_code_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OvertureDatasetZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(max_length=200)),
                ("geometry", models.JSONField()),
                ("bbox", models.JSONField()),
                ("boundary_hash", models.CharField(max_length=64)),
                ("source", models.CharField(max_length=120)),
                ("source_version", models.CharField(max_length=120)),
                ("attribution", models.CharField(blank=True, max_length=500)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="overture.overturedatasetsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "code"),
                "indexes": [
                    models.Index(
                        fields=["snapshot", "normalized_name"], name="overture_zone_name_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "code"),
                        name="overture_zone_snapshot_code_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("snapshot", "normalized_name"),
                        name="overture_zone_snapshot_name_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OverturePlaceZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_method",
                    models.CharField(
                        choices=[("POINT_IN_POLYGON", "Punto en polígono")],
                        default="POINT_IN_POLYGON",
                        max_length=30,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_links",
                        to="overture.overtureplace",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_zone_links",
                        to="overture.overturedatasetsnapshot",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_links",
                        to="overture.overturedatasetzone",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["snapshot", "zone"], name="overture_link_zone_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("place", "zone"), name="overture_place_zone_unique"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="overtureplace",
            name="zones",
            field=models.ManyToManyField(
                related_name="places",
                through="overture.OverturePlaceZone",
                to="overture.overturedatasetzone",
            ),
        ),
        migrations.CreateModel(
            name="OvertureReleaseCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Correcto"), ("FAILED", "Falló")],
                        max_length=20,
                    ),
                ),
                ("catalog_url", models.CharField(max_length=500)),
                ("releases", models.JSONField(default=list)),
                ("latest_release", models.CharField(blank=True, max_length=40)),
                ("manifest_sha256", models.CharField(blank=True, max_length=64)),
                ("error", models.CharField(blank=True, max_length=500)),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
