# Generated by Django 5.2.16 on 2026-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_outboundmessage"),
        ("catalogs", "0001_initial"),
        ("prospects", "0003_aianalysis_generation_aianalysis_next_retry_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="delivery_reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="gmail_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="gmail_thread_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="mime_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="sending_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="simulated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="outboundmessage",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="campaigns_o_state_ceb111_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message_id", ""), _negated=True),
                fields=("message_id",),
                name="outbound_rfc_message_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gmail_message_id", ""), _negated=True),
                fields=("gmail_message_id",),
                name="outbound_gmail_message_id_unique",
            ),
        ),
    ]
