# Generated by Django 5.2.16 on 2026-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_outboundmessage_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="in_reply_to",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
