# Generated by Django 5.2.16 on 2026-07-15 14:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("normalized_name", models.CharField(editable=False, max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("sort_order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("normalized_name",),
                        name="configuration_category_active_name_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("normalized_name", models.CharField(editable=False, max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[("NEIGHBORHOOD", "Barrio"), ("CUSTOM", "Personalizada")],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("location_text", models.CharField(max_length=300)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("sort_order", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("normalized_name",),
                        name="configuration_zone_active_name_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(max_length=200)),
                ("salesperson_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("products", models.TextField(blank=True)),
                ("differentiators", models.TextField(blank=True)),
                ("address", models.CharField(max_length=300)),
                ("website", models.URLField(blank=True)),
                ("signature", models.TextField()),
                ("additional_instructions", models.TextField(blank=True)),
                (
                    "relevance_threshold",
                    models.PositiveSmallIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("profile_version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("relevance_threshold__gte", 0), ("relevance_threshold__lte", 100)
                        ),
                        name="business_profile_relevance_0_100",
                    )
                ],
            },
        ),
    ]
