# Generated by Django 5.2.16 on 2026-07-22 02:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_seed_categories_and_zones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extractor_provider",
                    models.CharField(
                        choices=[("fake", "Mock (sin red)"), ("outscraper", "Outscraper")],
                        default="fake",
                        max_length=30,
                    ),
                ),
                ("outscraper_api_key_encrypted", models.TextField(blank=True, editable=False)),
                (
                    "outscraper_api_key_source",
                    models.CharField(
                        choices=[
                            ("ENVIRONMENT", "Entorno"),
                            ("ENCRYPTED", "Dashboard cifrado"),
                            ("NONE", "Sin configurar"),
                        ],
                        default="ENVIRONMENT",
                        max_length=20,
                    ),
                ),
                (
                    "outscraper_base_url",
                    models.URLField(default="https://api.outscraper.cloud"),
                ),
                (
                    "outscraper_max_cost_per_result",
                    models.DecimalField(
                        decimal_places=6,
                        default="0.010000",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("outscraper_batch_size", models.PositiveIntegerField(default=20)),
                ("outscraper_poll_seconds", models.PositiveIntegerField(default=30)),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("fake", "Mock (sin red)"),
                            ("ollama", "Ollama"),
                            ("openai-compatible", "OpenAI compatible"),
                        ],
                        default="fake",
                        max_length=30,
                    ),
                ),
                ("llm_model", models.CharField(default="fake-deterministic", max_length=120)),
                ("llm_api_key_encrypted", models.TextField(blank=True, editable=False)),
                (
                    "llm_api_key_source",
                    models.CharField(
                        choices=[
                            ("ENVIRONMENT", "Entorno"),
                            ("ENCRYPTED", "Dashboard cifrado"),
                            ("NONE", "Sin configurar"),
                        ],
                        default="ENVIRONMENT",
                        max_length=20,
                    ),
                ),
                (
                    "ollama_base_url",
                    models.URLField(default="http://127.0.0.1:11434"),
                ),
                ("openai_compatible_base_url", models.URLField(blank=True)),
                (
                    "gmail_provider",
                    models.CharField(
                        choices=[("fake", "Fake (sin red)"), ("api", "Google Gmail")],
                        default="fake",
                        max_length=20,
                    ),
                ),
                ("gmail_oauth_client_id", models.CharField(blank=True, max_length=500)),
                (
                    "gmail_oauth_client_secret_encrypted",
                    models.TextField(blank=True, editable=False),
                ),
                (
                    "gmail_oauth_client_secret_source",
                    models.CharField(
                        choices=[
                            ("ENVIRONMENT", "Entorno"),
                            ("ENCRYPTED", "Dashboard cifrado"),
                            ("NONE", "Sin configurar"),
                        ],
                        default="ENVIRONMENT",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_configuration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("outscraper_max_cost_per_result__gte", 0)),
                        name="integration_outscraper_cost_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outscraper_batch_size__gt", 0)),
                        name="integration_outscraper_batch_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outscraper_poll_seconds__gt", 0)),
                        name="integration_outscraper_poll_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("outscraper_api_key_source", "ENCRYPTED"), _negated=True),
                            models.Q(("outscraper_api_key_encrypted", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="integration_outscraper_cipher_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("llm_api_key_source", "ENCRYPTED"), _negated=True),
                            models.Q(("llm_api_key_encrypted", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="integration_llm_cipher_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("gmail_oauth_client_secret_source", "ENCRYPTED"),
                                _negated=True,
                            ),
                            models.Q(("gmail_oauth_client_secret_encrypted", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="integration_gmail_cipher_required",
                    ),
                ]
            },
        )
    ]
