# Generated by Django 5.2.16 on 2026-07-28 02:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("configuration", "0011_seed_workspace_message_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconfiguration",
            name="embedding_dimensions",
            field=models.PositiveSmallIntegerField(
                default=1536,
                validators=[
                    django.core.validators.MinValueValidator(64),
                    django.core.validators.MaxValueValidator(3072),
                ],
            ),
        ),
        migrations.AddField(
            model_name="integrationconfiguration",
            name="embedding_model",
            field=models.CharField(default="text-embedding-3-small", max_length=120),
        ),
        migrations.AddField(
            model_name="integrationconfiguration",
            name="embedding_provider",
            field=models.CharField(
                choices=[
                    ("fake", "Simulado (sin red)"),
                    ("openai-compatible", "OpenAI embeddings"),
                ],
                default="fake",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("embedding_dimensions__gte", 64), ("embedding_dimensions__lte", 3072)
                ),
                name="integration_embedding_dimensions_range",
            ),
        ),
    ]
