# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations, models


DEFAULT_AUTOMATIC_REPLY_PROMPT = (
    "Respondé como una persona de la empresa, no como una lista de datos.\n"
    "Contestá la pregunta concreta del cliente en la primera frase.\n"
    "Usá 1 a 3 párrafos cortos e integrá los datos relevantes con tus palabras.\n"
    "Si falta información, pedí sólo los datos mínimos necesarios y explicá para qué sirven.\n"
    "No menciones facts, tarjetas, contexto ni procesos internos.\n"
    "Cerrá con una próxima acción simple cuando ayude."
)


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0012_integrationconfiguration_embedding_dimensions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptconfiguration",
            name="automatic_reply_prompt",
            field=models.TextField(default=DEFAULT_AUTOMATIC_REPLY_PROMPT),
        ),
    ]
