# Generated by Django 5.2.17 on 2026-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0018_generic_initial_template_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptconfiguration",
            name="email_drafting_prompt",
        ),
        migrations.AddField(
            model_name="integrationconfiguration",
            name="relevance_llm_model",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="promptconfiguration",
            name="relevance_criteria",
            field=models.TextField(
                blank=True,
                default="Nos sirven los negocios que reparan, mantienen o rebobinan equipos con motor eléctrico: talleres electromecánicos, bobinados de motores, service de herramientas eléctricas, reparación de bombas, autoelectricidad, alternadores y arranques, mantenimiento industrial, reparación de electrodomésticos y de máquinas industriales.\nNo nos sirven los negocios que sólo venden equipos nuevos sin taller propio, ni los rubros sin relación con motores eléctricos.",
            ),
        ),
        migrations.AddField(
            model_name="promptconfiguration",
            name="relevance_filter_mode",
            field=models.CharField(
                choices=[
                    ("OFF", "Desactivado"),
                    ("OBSERVE", "Sólo marcar"),
                    ("LENIENT", "Prudente"),
                    ("STRICT", "Estricto"),
                ],
                default="LENIENT",
                max_length=20,
            ),
        ),
    ]
