# Generated by Django 5.2.17 on 2026-10-08 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_recoverycode_for_v2"),
        ("configuration", "0019_relevance_filter_and_remove_drafting_prompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SendModeSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("live_enabled", models.BooleanField(default=False)),
                ("live_enabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "live_enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enabled_real_sending",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="send_mode_setting",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("live_enabled", True),
                                ("live_enabled_at__isnull", False),
                                ("live_enabled_by__isnull", False),
                            ),
                            ("live_enabled", False),
                            _connector="OR",
                        ),
                        name="send_mode_live_activation_recorded",
                    )
                ],
            },
        ),
    ]
