# Generated by Codex on 2026-08-02

from django.db import migrations
from django.utils import timezone


def forwards(apps, schema_editor):
    KnowledgeFact = apps.get_model("automation", "KnowledgeFact")
    KnowledgeFactRevision = apps.get_model("automation", "KnowledgeFactRevision")
    for fact in KnowledgeFact.objects.order_by("pk"):
        revisions = list(KnowledgeFactRevision.objects.filter(fact=fact).order_by("-version"))
        if not revisions:
            continue
        latest = revisions[0]
        active_at = latest.approved_at or latest.created_at or timezone.now()
        if latest.approved_at is None:
            latest.approved_at = active_at
            latest.approved_by_id = fact.created_by_id
            latest.save(update_fields=("approved_at", "approved_by", "updated_at"))
        KnowledgeFactRevision.objects.filter(
            fact=fact,
            superseded_at__isnull=True,
        ).exclude(pk=latest.pk).update(superseded_at=active_at)


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0005_follow_up_topics"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
