# Generated by Django 5.2.16 on 2026-08-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0006_activate_saved_knowledge_revisions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replydecision",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("SHADOW_RECORDED", "Registrada en modo observación"),
                    ("NO_ACTION", "No corresponde responder"),
                    ("AUTO_ELIGIBLE", "Puede responder automáticamente"),
                    ("AUTHORIZED", "Autorizada"),
                    ("EXECUTING", "Enviando"),
                    ("COMPLETED", "Respondido automáticamente"),
                    ("MANUAL_REPLY_RECORDED", "Respondido manualmente"),
                    ("HUMAN_REQUIRED", "Necesita que lo revises"),
                    ("REJECTED_POLICY", "No autorizada por seguridad"),
                    ("FAILED", "No se pudo analizar"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
