import type { ThemeConfig } from "antd";

export const antdTheme: ThemeConfig = {
  // DESIGN.md fixes the runtime value to true; Ant Design 6 narrows this legacy boolean in its type only.
  cssVar: true as unknown as NonNullable<ThemeConfig["cssVar"]>,
  hashed: false,
  token: {
    colorPrimary: "#1E4B8F",
    colorSuccess: "#1F6E43",
    colorWarning: "#8A5A00",
    colorError: "#A32B24",
    colorInfo: "#1E4B8F",
    colorTextBase: "#16181C",
    colorBgBase: "#FFFFFF",
    colorBgLayout: "#F4F4F1",
    colorBorder: "#DEDEDA",
    colorBorderSecondary: "#EDEDE9",
    borderRadius: 6,
    borderRadiusSM: 3,
    borderRadiusLG: 6,
    fontFamily: "var(--font-plex-sans), system-ui, sans-serif",
    fontSize: 14,
    lineHeight: 1.43,
    controlHeight: 34,
    boxShadow: "0 2px 8px rgba(22,24,28,0.08)",
    boxShadowSecondary: "0 8px 32px rgba(22,24,28,0.14)",
    motionDurationFast: "0.12s",
    motionDurationMid: "0.18s",
    motionDurationSlow: "0.24s",
    wireframe: false,
  },
  components: {
    Layout: { siderBg: "#FFFFFF", headerBg: "#FFFFFF", bodyBg: "#F4F4F1", headerHeight: 52 },
    Menu: {
      itemBg: "transparent",
      itemSelectedBg: "#E8EEF7",
      itemSelectedColor: "#1E4B8F",
      itemHeight: 34,
      itemMarginInline: 8,
      itemBorderRadius: 3,
    },
    Table: {
      headerBg: "#EDEDE9",
      headerColor: "#4A4F57",
      cellPaddingBlock: 10,
      rowHoverBg: "#F7F7F4",
      borderColor: "#EDEDE9",
    },
    Card: { paddingLG: 20, boxShadowTertiary: "none" },
    Button: { primaryShadow: "none", defaultShadow: "none", dangerShadow: "none", fontWeight: 500 },
    Input: { paddingBlock: 6 },
    Tag: { borderRadiusSM: 3 },
  },
};
